### ISSUE TITLE
[Feat] complete WeatherUseCase, Data fetching

### ISSUE THREAD

**Issue by YunKi-H** [DeveloperAcademy-POSTECH/2024-NC2-A14-WeatherKit#10]
## Description
View 에 날씨 데이터를 연결하기 위해 WeatherUseCase 구현하기

## TODO
할 일 목록을 작성해 주세요

- [ ] LocationManager 에서 Location 가져오기
- [ ] WeatherManager 에서 날씨정보 가공해서 받아오기
- [ ] 화면에 표시될 데이터로 가공해서 저장하기
- [ ] View에 날짜별로 연결하기

### ETC
기타 참고사항을 작성해 주세요
