### ISSUE TITLE
[Feat] Calendar Detail, WeatherDetail

### ISSUE THREAD

**Issue by YunKi-H** [DeveloperAcademy-POSTECH/2024-NC2-A14-WeatherKit#12]
## Description
CalendarView, WeatherDetail 디테일 구현

## TODO
할 일 목록을 작성해 주세요

- [x] 주간 달력 날짜 선택시 컴포넌트 변경
- [x] 선택된 날짜만 백그라운드
- [x] 오늘 날짜엔 테두리
- [x] 날씨정보에 따른 WeatherDetail 표기 (기준 없음)

### ETC
기타 참고사항을 작성해 주세요
